---
docker:
  host: "https://boot2docker:2376"
  ssl_verify_peer: false

stacks:
  - name: torrent
    units:
      - name: base
        version: 1.0.0
        dockerfile: ./_base/Dockerfile
        startable: false

      - name: tracker
        version: 1.0.0
        dockerfile: ./tracker/Dockerfile
        dependant_unit_names:
          - base

      - name: seeder
        version: 1.0.0
        dockerfile: ./seeder/Dockerfile
        dependant_unit_names:
          - base
          - tracker

      - name: peer
        instances: 3
        version: 1.0.0
        dockerfile: ./peer/Dockerfile
        dependant_unit_names:
          - base
          - seeder
          - tracker
